baseURL = 'https://hujm2023.github.io/'
languageCode = 'zh-cn'
title = "hujm2023's blog"
theme = 'PaperMod'

preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true

hasCJKLanguage = true # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
disqusShortname = ""  # disqus_shortname
copyright = ""        # default: author.name ↓        # 默认为下面配置的author.name ↓



# change the location of the image cache
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    duplicateResourceFiles = false
    [markup.goldmark.extensions]
      definitionList = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = false
        eastAsianLineBreaksStyle = 'simple'
        enable = false
        escapedSpace = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = false
        [markup.goldmark.extensions.extras.insert]
          enable = false
        [markup.goldmark.extensions.extras.mark]
          enable = false
        [markup.goldmark.extensions.extras.subscript]
          enable = false
        [markup.goldmark.extensions.extras.superscript]
          enable = false
      [markup.goldmark.extensions.footnote]
        enable = true
        backlinkHTML = '&#x21a9;&#xfe0e;'
        enableAutoIDPrefix = false
      [markup.goldmark.extensions.passthrough]
        enable = false
        [markup.goldmark.extensions.passthrough.delimiters]
          block = []
          inline = []
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      autoDefinitionTermID = false
      autoHeadingID = true
      autoIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        useEmbedded = 'auto'
      [markup.goldmark.renderHooks.link]
        useEmbedded = 'auto'
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xhtml = true

[params]
  [params.author]
    name = "hujm.net@gmail.com"
    description = "个人技术博客，分享编程经验和技术心得"
    keywords = "编程, 技术, 博客, Golang, Python"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInTermsTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false
  [params.fuseOpts]
    isCaseSensitive = false
    includeScore = false
    includeMatches = false
    minMatchCharLength = 2
    shouldSort = true
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = true
    limit = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "index"
  path = "posts"

[[menu.main]]
  name = "首页"
  url = "/"
  weight = 10

[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 30

[[menu.main]]
  name = "分类"
  url = "/categories/"
  weight = 40

[[menu.main]]
  name = "搜索"
  url = "/search/"
  weight = 50

[[menu.main]]
  name = "关于"
  url = "/about/"
  weight = 60